### ISSUE TITLE
Problems opening DMN files in Camunda Modeler CE

### ISSUE THREAD

**Issue by bzinchenko** [dmn-tck/tck#131]
I installed Camunda Modeler Community Edition 1.11.3 from December 6, 2017 on Windows 7. As of the date of this writing, it is the latest version of Camunda Modeler officially offered on the site: https://camunda.com/download/modeler/

I carefully followed all instructions on how to setup the tool on the page below to the link. 

I have problems opening DMN models from DMN TCK test suite. I ve tried randomly around a dozen of TCK models, and all of them have roughly same warnings. Not much content is shown visually after opening. Also, I cannot edit models opened in this way.

Below are some screenshots and logs attached. Any advise on what should be done to fix these errors will be highly appreciated. Thank you.

![camunda_dmn_error](https://user-images.githubusercontent.com/5006818/37241676-c1da9302-2465-11e8-8415-3d57f70cd555.png)

**Comment by bzinchenko** [comment]
Some logs are here:
[0008-LX-arithmetic.txt](https://github.com/dmn-tck/tck/files/1799311/0008-LX-arithmetic.txt)
[0014-loan-comparison.txt](https://github.com/dmn-tck/tck/files/1799312/0014-loan-comparison.txt)

**Comment by falko** [comment]
Hi Boris,

thank you very much for your feedback! It is a known issue that some models, which lack Diagram Interchange (DI) information, are nevertheless detected as DRDs even though nothing can be displayed without DI. This is in part due to the fact that DMN 1.1 does not have an official DI.

This issue has been fixed in our [new DMN Modeler](https://blog.camunda.com/post/2018/03/camunda-modeler-1120-alpha-3-released/), which by coincidence had its [first alpha release](https://blog.camunda.com/post/2017/12/camunda-modeler-1120-alpha-released/) on the very day you opened this issue.

Despite all this, the focus of the DMN TCK is the execution of DMN models. So in order to reproduce test results of Camunda, you would need to deploy the DMN files to our engine. In our product, a deployment is not done through the modeling tool.

Cheers,
Falko

**Comment by bzinchenko** [comment]
Hello Falco

Excellent news! I m going to try this new release and also will recommend it to our partners who are working on DMN models using Camunda. It was exactly my concern for their models created in Camunda CE in respect to DMN compatibility, which caused me to raise this issue. 

I agree that raising it in Camunda forums might be more relevant. But since the issue concerned also DMN TCK scope, I decided that here is equally suitable place for discussion.

Curiously, I m definitely aware on absent DI standard and, moreover, on absent DI info in most of TCK diagrams. It was exactly my curiosity for visualization, which caused this experiment.

I had a decent hope that Camunda will make a sensible display of imported entries in a perceptible way to back my understanding of the samples. 

Anyway, as Keith correctly pointed, it does not matter, as far as execution is not affected. Looking forward to run some execution tests in Camunda very soon.

Thank you again for clarifications and announcements!

Sincerely
Boris Zinchenko

**Comment by bzinchenko** [comment]
Hello Falco

I followed your valuable advice and installed latest alpha:
https://camunda.org/release/camunda-modeler/1.12.0-alpha-8/
camunda-modeler-1.12.0-alpha-8-win32-ia32.zip
All files, which had errors in previous version, open fine now. 
Thank you!

Sincerely
Boris Zinchenko

**Comment by falko** [comment]
Hi Boris,

Camunda Modeler 1.12.0 is now also available as a [stable release](https://camunda.com/download/modeler/). If you have further feedback feel free to talk to us in the [user forum](https://forum.camunda.org/c/modeler) or open an issue on [GitHub](https://github.com/camunda/camunda-modeler/).

Cheers,
Falko
