### ISSUE TITLE
Sepsis mitigation logic

### ISSUE THREAD

**Issue by bzinchenko** [dmn-tck/tck#146]
This issue is created as a discussion point for preparation of submission of real life DMN example, which solves important problem in healthcare. 

Provided are original DMN file and respective XML file created automatically from the model by our test case generator. DMN was created in Camunda Modeler. We kindly ask for evaluation of created XML in respect to complimentary DMN model. 

When XML will be confirmed as valid, we will fill it with real data and submit it to main test list. Please do NOT edit XML file manually. It is automatically generated. We need directions on inconsistencies to improve the code, which was used to create this test file. Thank you.

[0201-sepsis-mitigation.zip](https://github.com/dmn-tck/tck/files/1954965/0201-sepsis-mitigation.zip)

**Comment by agilepro** [comment]
Not really a full test yet.  Just a template.  That is not really all that useful.  Go back to the requirements document and fill in with values that must be coordinated.  That is, when an indicator is at a certain level, the model must produce a certain output.  That is where the value of a test lies.

We can automatically test a XML when it has valid values in it.

At this time, without valid values, you will get an error, and it will be hard to tell whether the problem lies in that you have invalid test inputs, or whether your test structure is wrong.  You will get an error in any case.  Make a valid test, and then ask others whether it is completely valid.

**Comment by agilepro** [comment]
discussed, and outdates.
