### ISSUE TITLE
Exorbitant input in "0004-lending"

### ISSUE THREAD

**Issue by bzinchenko** [dmn-tck/tck#150]
In this example test case "001" has input node "RequestedProduct", which is not defined in information requirement of tested decision "Adjudication".

**Comment by bzinchenko** [comment]
It seems happening because this test runs at once two decisions. Is it required to have only one decision per test case or there can be arbitrary amount of decisions included into a test case?

**Comment by agilepro** [comment]
The only thing that we care about is that we have test cases which make calls on decision models which return consistent results.  We have no specific requirements on the decision models themselves beyond that they must be a valid decision model according to the spec.  

This means, that someone might employ an existing decision model, and then only test part of it.  We don't require that the tests cover all possible cases for the decision.  Testing the correctness of the decision model is not our goal.   We test only that it executes the same in every engine.

There is no requirement that there be a single decision table per test.  Any valid DMN decision model is a possible for use in a test case.

The test case might not define values for every input.  Some tests are testing what happens when an input is not provided a value.

**Comment by bzinchenko** [comment]
Thank you so much for this detailed comment, which entirely clarifies the subject. I strongly believe that this excellent summary should be a part of DMN TCK test preparation guidelines, not to be lost here.
