### ISSUE TITLE
Joining the effort

### ISSUE THREAD

**Issue by StrayAlien** [dmn-tck/tck#192]
Hi all,

First of all.  Congrats to all for a fine specification and well done to the contributors here on the TCK effort.

Secondly, apologies for this posting in 'issues'. 

I have followed the instructions for joining the TCK effort and things have been very quiet.  I've sent of some emails and received no responses.  Hence this post.  Again apologies.  I am aware it is pretty likely folks may be on vacation in the US/Canada at the moment.  I am in Melbourne, Australia.

Also, my apologies for being a complete DMN newb.  My relationship with DMN and FEEL started from absolute zero maybe three weeks ago.

As part of research for a possible new venture I am currently prototyping a v1.2 DMN and FEEL 'execution' implementation (no modelling as yet).  After a couple of weeks or so of some pretty intense pizza-under-the-door coding I am nearing the end-game of the current TCK compliance tests.  It may be of interest to some that the prototyping platform is Typescript. The TCK is being run by Nodejs and Mocha. 

If I may, I wish to contribute back to the TCK.  There are gaps in the suite so this post is a starting point to find out how I can help.  There are also some large-ish gaps in my understanding and more than a few spec ambiguities that need resolving for me.  I have some questions for sure.  I doubt I can finish it without getting stuff resolved.

At any rate, I am keen to make a start here and get the ball rolling and understand what the process is.

Many thanks,

Greg McCreath.

**Comment by StrayAlien** [comment]
sure is quiet around here ....

**Comment by falko** [comment]
Hi Greg,

please contact @agilepro 
He wanted to get back to you already, but might be on holiday this week.

Cheers,
Falko

**Comment by tarilabs** [comment]
Hi Greg,
also you may want to follow a few of the pointers in this page: https://github.com/dmn-tck/tck#how-to-join "How to join" and if you have a chance to participate in the weekly calls I believe would be the most easy way to get started!
Hope this helps,

**Comment by StrayAlien** [comment]
Hey all, thanks for responding.  There is hope!  :-)  Falko, thanks.  I'll do that.  Tarilabs, thanks as well.  The instructions there were the first thing I did almost a month ago now.  I emailed Keith (on two different addresses), joined the circleweaver thing, emailed Bruce, posted here and waited a week.  I would be keen on joining those calls.  No doubt they are at 3am my time or something unsociable.  :-)

For now, I have got myself through to the end of the current TCK tests.  I have a very long list of things that are issues or are not covered etc etc.  Should I just spin up issues here?  There might be 30-40 or so of them though - ranging from large through to small.  Not sure if this is what you discuss at the weekly call.

Thanks again,

Greg.

**Comment by tarilabs** [comment]
> No doubt they are at 3am

Sorry just out of curiosity, which Timezone are you based in, please? :)
Because from what I can see current time schedule allows for this call to be at lunch-break for Americas and after-working-hours in Europe, and indeed might be getting late from people joining from Middle-East/Asia..

Anyway first of all congratulations for working through all the TCK tests, is not always a trivial feat as some test are really stressing all the combination of operators, I am thinking of the generated test contributed which for instance checks the Binary Expression possible combinations!

I would advise is best to start with the most specific questions you may have about some test case. You could raise a GitHub issue for instance if a DMN model / test is not clear to ask for the clarification. Personally, I would do progressively, as I found out sometimes resolving a specific issue actually resolved other ones at the same time. Wdyt?

**Comment by tarilabs** [comment]
Oh wow! I have a couple of friends there, wish to visit one day :)

Concerning _Decision Service_ specifically there is currently no coverage because the DMN specification of Decision Service within DMNv1.1 is broken in the serialization part. Hence it would have not been fair to cover with the TCK as would have required to agree on the serialization off-the-spec. This issue has been fixed with DMNv1.2 so I would expect we will be able to have some TCK test to cover for Decision Service in the next iteration as we are migrating to DMNv1.2 (ref meeting notes from Keith).

If you have some DMN test which cover other functionalities, for instance function invocations, etc please don't hesitate to submit them. In the wiki I believe there are some documents which describe how you can contribute new tests. We are always looking for contributors of new tests, so your submissions will be most welcome! I would strongly recommend to submit them with the DMNv1.2 format if you can, as mentioned in the minutes, we are in the process of migrating the entire test suite to DMNv1.2.

If you need any specific assistance with this don't hesitate to let us know, and personally I will always try to support as best as possible.

Also if you have a list of gaps which you identified you can indeed post them here and we'll see from there how to best proceed in the details.

Hope this helps!

**Comment by StrayAlien** [comment]
Thanks tarilabs, understood re the move to 1.2.  And thanks for the offer of support.  I'll take you up for sure. There are still some mysteries for me..  Keith has been in contact so I'll try to get the meeting notes from him.

Re Melbourne.  Sure thing - if you're ever this way, lemme know.

**Comment by StrayAlien** [comment]
closing this.  Will open a new issue with notes re TCK.
