### ISSUE TITLE
Usage of string() in test assertions

### ISSUE THREAD

**Issue by StrayAlien** [dmn-tck/tck#199]
A number of the tests rely on the output of the string() function to make assertions.

The spec does not define what the output or format of the string() function is for different types.  An implementation could choose to output 123 as a string like "one two three".  That would be legal.  The spec does not cover it.

I think maybe it should, but, that is another matter.

A valid implementation could fail the TCK based on how it outputs strings.  At this point, those tests are asserting on a 'convention' not the specification.

Though, this is quite important for portability of models.  Might I suggest that we add another folder to the TCK for 'by-convention' tests, where we assert on agreed-upon conventions established outside of the spec.  The test results of the folder perhaps should be non-reportable on the tck results website.   

Perhaps, ultimately, this is how we gain commonality for ambiguities, and maybe get them rolled into future spec versions. 

Comments welcome.

Greg.

**Comment by agilepro** [comment]
Right.  The purpose of the TCK is for exactly this situation.  No spec can possibly be complete, and so no spec can guarantee interoperability.   We interpret the written word as best we can, and when we run into implementation problems, we propose clarification to the standard group.

The tests as written represent the de-facto standard.  The very purpose of the TCK is to be more specific on exactly how each aspect works, filling in for any ambiguity in the spec.  We are NOT trying to allow for all varieties of implementation, but trying to get closure on one specific approach in order to assure interoperability between implementations.

I certainly would welcome a document that specifies how to disambiguate the ambiguities if you would like to collect that together.   Similarly, you could simply write a test (or set of tests) that clarify correct behavior.  It seems to me that the test is far more useful than the document because it can automatically confirm that all implementations comply.

My recommendation is to try to implement such that all tests run.  Use test driven design.  When your implementation runs into a problem, if you think that the spec is guiding implementations in a different direction, then raise that as an issue and we can discuss.  Your silly example would surely be rejected, however in a real case we might have to discuss.  We will need to come to agreement in order to change any existing test.  

If you are worried about other ambiguities, please write a few tests to clarify as best you can.  We allow anyone to add test cases. If they don't run in the existing engines we will correct them.  But you don't have to prove that the tests run everywhere before submitting them.

**Comment by StrayAlien** [comment]
Thanks for the clarification.   

Please understand I mean no offence commenting here I am still understanding the spec and indeed, the TCK.  It is important for implementors  to understand the TCK is not to black/white verify operation against the spec, but to create common ground.  It is a sensible, tangible approach and I agree with it.  The last TCK I implemented to was entirely the opposite - absolutely black and white and near on 45000 tests as I recall and it was the 'law'.

Perhaps in those cases where the tests make assertions not in the spec - or fill in ambiguities, it may still be worth tracking them - even is that is just a test label or a comment on the test or a readme.md. Just lets newbie implementors know whether they are dealing with convention or specification I guess.  The above string example is simple but when we get to (say) assertions on type conformance for lambdas it may not be so obvious whether the test covers the spec or agree-upon convention.

Re submitting tests, sure -  though still finding my feet and presently it seems quite a number of the things I see are actually differences between spec versions - less work for everybody just to seek some clarification first I guess.

Thanks again.  Appreciated.  Closing.

**Comment by StrayAlien** [comment]
re-opening as a result of discussions in https://github.com/dmn-tck/tck/issues/206.

**Comment by StrayAlien** [comment]
@tarilabs @agilepro.  Thanks Matteo, comments in #206 noted. My original suggestion (above) was to have tests but keep them separate so that it was apparent to implementors the tests were not spec - but were 'recommended' as part of the standardisation effort.  I am not for 'forcing' people to do stuff, but, the goal of this TCK effort is portability, so, I do believe the tests are needed to help that.

Maybe the extra folder idea is still valid?

Greg.

**Comment by agilepro** [comment]
We have discussed at a couple of meetings.  I have sent a message asking people to weigh in on this issue.

https://s06.circleweaver.com/weaver/t/wfmc/dmn-reference-implementation/noteZoom3397.htm

I expect them to respond IF they are OPPOSED to testing string values.  If no objection raised in the next week, we will move forward as accepted.

**Comment by StrayAlien** [comment]
test cases moved to non-compliant for now.
