### ISSUE TITLE
not possible to write tests for string() on some data types

### ISSUE THREAD

**Issue by StrayAlien** [dmn-tck/tck#206]
Hi all,

string() for some data types is ambiguous.  For example: `string(string)`.  Is this requesting a textual representation of the string _type_ or the string() _function_. Same applies for date, time, date and time, number, years and months duration.

So, no can do coverage there.

Is this the right place to mention stuff like this?

Greg.

**Comment by agilepro** [comment]
Should we precisely control the conversion of values to strings? Matteo rightly points out that this could be controversial. 

> ... a FEEL expression like string([1, 2, 3, "foo"]); on pragmatic terms this test case would impose it to be [1, 2, 3, "foo"] only, but [ 1 , 2 , 3 , "foo" ] would actually be a valid output too

- One position is that if the spec allows two ways to do something, we should not constrain the implementations to one. 
- The other position is that we desire interoperability, and if we allow multiple ways to do things, then the tests will not be interoperable. There will always be little annoying differences that will resulting tests running differently, and failing inappropriately.

I think we have the opportunity to precisely define exactly how strings are produced. A spec can never possibly do that. By providing tests that prove precise representation, we give a tool to vendors who might implement multiple different ways, a way to implement exactly the way that they should.

This is not exceeding our charter: the purpose of the TCK is precisely to give tools to make sure that every implementation is exactly the same. Is there a limit to this? I don't know, but I see every benefit in testing all behavior exactly, and no real downside to it. That is, I don't see any benefit in allowing multiple ways to any degree.  Do you agree?

When consuming and parsing, the number of spaces is optional in many places.  That makes sense.  But when generating, I think there should be a specific canonical form which is precisely defined and is repeatable.

**Comment by StrayAlien** [comment]
Thanks @agilepro, @tarilabs.   I agree we should conform to something - despite it not actually being in the spec.  Conforming is better than not-conforming for a TCK I think.  Conforming is not actually that hard.  We need to decide on spaces, escaping, and when to quote context keys.

Regarding this particular issue, it doesn't so much have to do with string() conformance more to do with ambiguity.  A number of types share names with functions so, for example, it is not possible to determine what is meant by this:

`string(string)`

it could be requesting the string representation of the string _type_, which (speculatively could be "string"), or the string _function_ which might be something like "(any) -> string".

We could decide one gets priority over the other and do something like:

> with string(), the 'from' parameter is resolved from the scope (and parentage).  On failure to find anything there, check for a type of the same name.

I think this seems reasonable as a) we'll all be checking the scope for the thing to stringify, and b) we'll all be looking at the 'type registry' for a type for stringify.

We just have to agree that thing in the scope take priority and therefore it is not possible to get the string representation of some types.   

All advice welcome.

Greg.

**Comment by tarilabs** [comment]
While in general I agree with https://github.com/dmn-tck/tck/issues/206#issuecomment-447430416 I believe context also is important: from my perspective the `string()` function in pragmatic terms is meant to provide an analogous to the Java `toString()` method, hence we can expect the output produced by any engine **must** be correct, but is not important in this context to push all Vendors to comply with also _formatting_ issues like the number of spaces.

Most importantly in this analogy, further it would be wrong for DMN practitioners to rely on a _specific_ output when the DMN spec does not impose one specifically --likewise one cannot rely in Java on any specific output of the `toString()` for further parsing.

I think one can reasonably agree with this analogy, otherwise the DMN spec would have mandated a specific output formatting (number of spaces between list items, etc.).

That is why with https://github.com/dmn-tck/tck/pull/204#discussion_r241393226 I was proposing for the purpose of TCK testing the FEEL `String` function, we could feed the result back into a `replace` call, in order to strip spaces and check the semantic output normalized in this way.
I preferred to give a complete explanation of my perspective.

**Comment by StrayAlien** [comment]
@tarilabs @agilepro re-opening issue https://github.com/dmn-tck/tck/issues/199.  The discussion is certainly valid, just this issue is about something else.

**Comment by agilepro** [comment]
Just reflecting on past experience where a strict definition was a problem, and that was when I was at Netscape in the 90's with HTML.  Most people think that the <PRE> tag preserves all the newline characters in the contained block so that a newline causes the following characters to appear on a next line.  However, in reality it preserves all the newline characters AFTER the first one.  People typing like to start the block at the beginning of the next line after the <PRE> tag, and so that first newline must be ignored, otherwise you get these annoying blank lines before the code block.

Naive parsers of HTML don't know this, but if you compare the output to that of another browser, you quickly learn that if you don't ignore the first newline, the display looks ugly.   The point, of course, is that the HTML spec does not mention anything about ignoring the first newline.  We want browsers that look and act the same, and so implementers had to learn how reality differed from the spec.

What an ADVANTAGE it would be to have a bunch of tests that checked that output was exactly the same!   While it may seem arbitrary, having the exact same representation of strings would be a huge advantage.  Having a set of tests that could quickly and easily tell you that all your string generation was identical to all other implementations would be huge as well.  

Consider the other scenario:  let's imagine that there was a vendor who refused to follow the others.  This vendor insists that their formatting is "better" in some way.  If it is better for one user, then it is better for all users.  Why shouldn't that vendor bring the issue up with RTF and make it part of the spec?  There should be no such thing as different "styles" of DMN for different users, because this is supposed to be a universal representation. However, if different "styles" make sense, then why not bring it to the RTF.  I think it is highly unlikely that any vendor will come up with a reasoned response as to why they format the string differently.  Most of the differences are purely arbitrary, and most vendors will simply change the way they output to match everyone else.   Once done, all the results are interchangeable. 

In the end, I see only a big benefit from testing string output for consistency.  I see no significant downside.  Furthermore, it is our very purpose to fill in the missing details of the spec with clear tests that interpret the specification as unambiguously as possible.

**Comment by agilepro** [comment]
Discussed in meeting.  This is still an unclear point about hte spec, and we still want to consider what needs to be done if anything.

**Comment by agilepro** [comment]
We decided to include these tests in the non-compliance folder, and this ha been done.  So the issue is closed
