### ISSUE TITLE
setting up a nodejs test runner

### ISSUE THREAD

**Issue by deostroll** [dmn-tck/tck#210]
The readme gives instructions to setup a jUnit test runner. Our engine is written entirely in nodejs. Therefore, we need to execute these test cases using a testing framework called mocha. 

My maven know-how is not so strong, but I believe the following command `mvn clean install -P drools` should pull the drools engine dependencies from maven repositories and run the test cases.

Since ours is a nodejs based engine, technically speaking, we have to run an `npm install` to download the testing framework (all of this will be specified in a file called `package.json`), and then run something like `npm test`. 

Hence, maven has to do something to the above effect. At least that is what I think. I want to know how this can be done, and, also would want guidance on a better approach if available.

**Comment by StrayAlien** [comment]
Hi @deostroll, indeed the test runner there is a Java-based (junit) test runner.  For nodejs/mocha you'll have to create your own I'm afraid. 

I did a (closed source) nodejs impl recently and also dealt with the mocha thing.  Some things to keep in mind:

* you'll need to parse the test/model XML.  nodejs is not terribly strong in this area. 
* many of the tests have multiple assertions per test - that is, there are multiple result nodes per testcase.  In your mocha test runner consider how you nest the fdescribe()'s.  I chose to treat each result node as a it() test and used nested fdescribe()'s to create a hierarchy above them.
* the test case XML has xsi types in it - so respect those.

Some thing to consider in your nodejs impl:

* nodejs has no notion of 128 bit maths.  You can likely pass many tests by rounding to 9 decimal places.  But it still isn't true to the spec.
* nodejs/JS regex is different to the spec requirements.  
* the date/time/duration aspects of the spec are *very* (**very**) difficult to support in nodejs/JS.  JS date are simply not up to the task.  You can use some of moment.js to get some stuff done,  and some of luxon, but they both fall quite short of what is needed.  Both have bugs, both parse dates/times/durations differently to what is required and both perform date/time/duration arithmatic differently to what the spec requires.

Regards,

Greg.

**Comment by agilepro** [comment]
Greg's suggestions are all good.

About the math: we decided to compare numeric equality to only 8 digits precision which should be good enough to test the rule logic, without getting into trouble with testing the precise implementation of the numbers. 

My team implemented a test runner that runs in a browser, and then calls the rules on the server through a web service call.  The parsing of the XML was not a problem in the browser, and I don't see why it would be a problem in Node, however consider the browser option if there is any difficulty. 

Writing a runner is not difficult, you read the XML file and call the model with the parameters.  Since your rules are implemented in JS, and there is no standard on how to invoke a rule in JS, your runner is somewhat proprietary, however if you do get it running, consider sharing it with the TCK -- we would love to have a JS-based runner.

**Comment by StrayAlien** [comment]
Hi Keith,

> The parsing of the XML was not a problem in the browser, and I don't see why it would be a problem in Node, however consider the browser option if there is any difficulty.

Good tip.

As an fyi, the in-browser JS has access to the browser DOM so XML DOM is in-the-box.  nodejs has no DOM.  There are some libs out there, but to be honest, they're not that great. So it can be done, no problem (I did it recently), but it sure isn't a strong point of nodejs.  I guess you might also be able to use phantomjs.

**Comment by agilepro** [comment]
I think the question is answered
