### ISSUE TITLE
0087-chapter-11-example

### ISSUE THREAD

**Issue by opatrascoiu** [dmn-tck/tck#303]
Decision Adjudication does not have an expression. Seems to be redundant.

```
	<semantic:decision id="_4bd33d4a-741b-444a-968b-64e1841211e7" name="Adjudication">
		<semantic:variable name="Adjudication" id="_12f285f8-ae4e-4421-98bd-d9b1fd236e10"/>
		<semantic:informationRequirement id="_290b4df4-ffe6-4106-9e22-07a339146161">
			<semantic:requiredInput href="#_d14df033-f4a2-47e3-9590-84e9ff04db4e"/>
		</semantic:informationRequirement>
		<semantic:informationRequirement id="_5046fe50-d2f2-4e54-b1e4-e7de5ffd4bb2">
			<semantic:requiredInput href="#_e91de815-22ba-431c-8b46-55891f2a1ef6"/>
		</semantic:informationRequirement>
		<semantic:informationRequirement id="_3a4e82d4-7a7a-43c7-9528-efa8b9e69e7c">
			<semantic:requiredDecision href="#_ca1e6032-12eb-428a-a80b-49028a88c0b5"/>
		</semantic:informationRequirement>
		<semantic:informationRequirement id="_7fc499b6-a180-4e16-80cd-58df441f4d38">
			<semantic:requiredInput href="#_34cd3187-8764-4249-959d-2664bf9f1847"/>
		</semantic:informationRequirement>
		<semantic:authorityRequirement id="_dabc7bb7-b8be-4654-9f7e-455481cb1c4e">
			<semantic:requiredAuthority href="#_989d137f-86ff-4249-813f-af67c08a2762"/>
		</semantic:authorityRequirement>
	</semantic:decision>

```

**Comment by tarilabs** [comment]
It is actually as from .ZIP file example from OMG

DMN 1.2 RTF examples.zip | Archive | DMN/20180505/examples.zip | dtc/18-05-13
-- | -- | -- | --

I believe it is meant as an example of a non-automated Decision; that is the reasons the test case stick only to invoking the top level decision with a defined decision logic, such as "Strategy" and "Routing"
![image](https://user-images.githubusercontent.com/1699252/57712954-d2b57480-7671-11e9-910a-16fd18846a7c.png)

from the DMN spec:

> The Adjudication decision requiring Applicant data, Bureau data, Supporting documents, and the Routing decision, has no associated decision logic.

**Comment by StrayAlien** [comment]
I also noticed that - I mean that it says it has no logic and is meant not to .. so I figured decisions can have no logic if they are not a required input to anything.    Warrants a specific test.

**Comment by tarilabs** [comment]
> so I figured decisions can have no logic if they are not a required input to anything

I don't concur.

You can have these Decision without decision logic to define their type via `typeRef`. The actual value the Decision take, could either be assigned manually (for instance this example from CH11 on the spec I believe is meant to be set by a human) or externally.

The rest of the model (is not the case for CH11) can still continue to evaluate correctly, as long as the Decision obtains a valid value. So I do not share the same view that these kind of Decision must not be a informationRequirement of another DRGElement, and for this to be asserted in a specific test.

But this is now going off in a separate direction...
This github issue is about the Decision without a decision logic from CH11 of the spec; I believe this is intentional as provided by the zip reference, DMN spec quotes, and screenshot I provided. I also highlighted the TCK test case do only call for those top level decision having a decision logic; I've also added on @StrayAlien suggestion more fine grained test in the test itself. I believe TCK test case 0087-chapter-11-example is correct.

**Comment by StrayAlien** [comment]
Not quite sure I get how, in an automated decision microservice, - a decision with no logic (that was a required input to another decision) obtains a value beyond null/error.

In a workflow, yes, but a decision microservice ... ? Sounds like an error to me.

**Comment by tarilabs** [comment]
> What would you expect to happen?

Can we have it in a separate thread/github issue, please?

This github issue is about the Decision without a decision logic from CH11 of the spec; I believe this is intentional as provided by the zip reference, DMN spec quotes, and screenshot I provided. I also highlighted the TCK test case do only call for those top level decision having a decision logic; I've also added suggestion more fine grained test in the test itself.

I believe TCK test case 0087-chapter-11-example is correct.

**Comment by opatrascoiu** [comment]
The model for 0087-chapter-11-example is correct from the syntactic point of view - XSD & metamodel.

But it contains a decision that has not semantics associated with (incomplete specification). All the tests  pass because the decision is not used as input anywhere (redundant). 

What we have here is similar to having redundant code that throws an unsupported exception in Java.

The question is if we want to keep this redundant / incomplete specified decision or delete it. My preference is to delete it.

**Comment by agilepro** [comment]
Discussed in meeting.  There are "decisions" which do not have decision logic.  From an automation point of view, the model is incomplete, however it is possible to ask a human to make those unspecified decisions.   In this respect, we are testing only the decisions which are fully automated, and ignoring the decisions which are not automated.   In the meeting we agreed that this is OK and we should only invoke the automated decisions.

Should we have a negative test to assure that the engine returns null for the decision that has no logic?  What about engines that "pop up a window for human input?"   Seems like the engine should be stateless and unambiguous and without side effects.  Maybe we should add a negative test in the future, but would prefer getting the positive tests settled before worrying about negative tests.

**Comment by agilepro** [comment]
Discussed with Octavian, and agree we can close this.  Partially specified models are not necessarily an error.
