### ISSUE TITLE
clarification on suite 0085 - test `002_a` vs `010` - bad decision service params

### ISSUE THREAD

**Issue by StrayAlien** [dmn-tck/tck#349]
Hi all,

Looking to clarify an assertion difference between the two above tests.  The assertion on `010` has changed from the original PR so trying to understand it.

Both tests are ultimately for a decision service with bad params, and therefore both were anticipating a null result:

- `020_a` calls a decision service directly passing zero parameters when a single param is expected.  We assert on a null result (with error flag) which we all seem to agree is correct.  This is consistent with TCK tests for BKMs and built-in functions asserting the same.

- `010` is pretty similar - it calls a decision that simply returns the value of decision service invocation - but it passes a badly named param to the decision service.  We have quite a few tests for BKMs and built-in functions asserting the result of an invocation with a badly named param is null.  As such, the original PR has the ultimate result being asserted as null (with error flag) on the basis this is a bad invocation.  The test now asserts otherwise - it seems to assert that the decision service invocation is okay, with some value within the context it returns being null. 

I've been staring at it but can't figure it out!  

Many thanks,

Greg.

**Comment by tarilabs** [comment]
`010`: is the result of correctly asserting decision service result, with the evaluation breakdown as discussed here and : https://github.com/dmn-tck/tck/pull/265#issuecomment-493759855

This should clarify your enquiry.
Multiple vendors concurred during the meeting and supplied results for the same.

Please don't forget to mark issue as resolved if you don't need further clarifications.

**Comment by StrayAlien** [comment]
Hi @tarilabs.  Thanks very much for the response.  I do understand that.  I'm pretty sure we have tests for that 'somewhere'.  However, this test is for a _bad_ parameter, not an _unsupplied_ one as per your reference.

We have tests for passing badly named params to BKMs (I am pretty sure somewhere) and built in functions (examples below) that result in them being `null`.  Here are some examples, but there are quite a few others:

https://github.com/dmn-tck/tck/blob/master/TestCases/compliance-level-3/0050-feel-abs-function/0050-feel-abs-function-test-01.xml#L60

The above has one param so could be ambiguous, but this has one of two params being badly named and thus returns null on that basis:

https://github.com/dmn-tck/tck/blob/master/TestCases/compliance-level-3/0067-feel-split-function/0067-feel-split-function.dmn#L69

The intention of the above tests (and others similar) is to assert that a badly named param passed to a function/bkm/etc is an invalid invocation will result in a null result with an error flag.

The test result on 010 appears to be inconsistent with that. 

Greg.

**Comment by tarilabs** [comment]
Let's focus on your original question. If there are other problems let's tackle them separately but again focusing one allegedly problem at a time.

Your original question is about `decisionService_010` inside `0085-decision-services.dmn` test case.

```
    <decisionService name="decisionService_010" id="_decisionService_010">
        <variable name="decisionService_010"/>
        <outputDecision href="#_decision_010_2"/>
        <inputDecision href="#_decision_010_3"/>
    </decisionService>
```

and because `_decision_010_3` is named `_decision_010_3` the full signature is:

```
decisionService_010(_decision_010_3)
```

with 1 parameter named `_decision_010_3`.

It gets invoked as: 

```
decisionService_010(foo: "bar")
```

so the invocation is by using **named parameter** style invocation.

From the spec:

> 10.3.2.13.5 Positional and named parameters
> An invocation of any FEEL function (built-in, user-defined, or externally-defined) can use positional parameters or named parameters. If positional, all parameters SHALL be supplied. If named, unsupplied parameters are bound to null.

As the named parameter style invocation does NOT supply the `_decision_010_3` parameter, that is bound to null.

It would be completely equivalent of writing:

```
decisionService_010(_decision_010_3 null, foo: "bar")
```

it follows:

```
decision_010_1 : decisionService_010(null)
decision_010_1 : {
        decision_010_2: "foo " + null
}

final result:

decision_010_1 : {
        decision_010_2: null
}
```

as originally reported and discussed here: https://github.com/dmn-tck/tck/pull/265#issuecomment-493759855

**Comment by StrayAlien** [comment]
Thanks again @tarilabs, I do understand that missing params are considered as a null param.  Thanks.  And I have read the comments on #265.

Apologies, but, at the expense of repeating my previous post, this was not a test for a missing param, it is about a _bad_ param.  The tests I reference in my previous post are specifically to assert that a badly named param results in a null - even if other valid named params are passed.  We have a number of those tests, and, as you say, multiple vendors have concurred this is the case.  The tests normally say something like "incorrect named param" or something.  Just looking, there are five called "will error when wrongly named param".

The intention of this test was to assert the same thing for a decision service as we already assert for other things.

If badly named params are to be totally ignored then that is another matter - it would made the test as it is now valid, but we've then got a fair number of already-agreed upon tests asserting the opposite - and this was their intention.  

Not trying to be controversial here, or dismiss anybody's work, just trying to understand why we're treating this case differently to the other existing test cases that preceded this one.

I hope that helps makes more sense. 

Greg.

**Comment by tarilabs** [comment]
> but we've then got a fair number of already-agreed upon tests asserting the opposite

can we speak with data, please?
You linked to two examples beyond this test, beyond decision service test.

### Example 1 linked beyond decision service.
The linked example is: https://github.com/dmn-tck/tck/blob/master/TestCases/compliance-level-3/0050-feel-abs-function/0050-feel-abs-function-test-01.xml#L60
which is for:

```
abs(n:-1)
```

as corresponding to https://github.com/dmn-tck/tck/blob/f212e3ade5aeeb252386cc83ac1473313503a2cc/TestCases/compliance-level-3/0050-feel-abs-function/0050-feel-abs-function.dmn#L64

that is a named parameter style invocation; hence, in my understanding of **10.3.2.13.5 Positional and named parameters**, applies again the principle that _unsupplied parameters are bound to null_, my understanding:

```
abs(n:-1) // original
abs(number: null, n: -1) // applies 10.3.2.13.5 
null // result, cannot absolute a null.
```

and then because trying to invoke the built-in FEEL `abs()` function for a null, you cannot absolute a null, hence result is null.
The test is showing the non-automated, helper flag for an error is expected to be raised, which is fine [link](https://github.com/dmn-tck/tck/blob/f212e3ade5aeeb252386cc83ac1473313503a2cc/TestCases/compliance-level-3/0050-feel-abs-function/0050-feel-abs-function-test-01.xml#L62).

### Example 2 linked beyond decision service.
The linked example is: https://github.com/dmn-tck/tck/blob/master/TestCases/compliance-level-3/0067-feel-split-function/0067-feel-split-function.dmn#L69
which is for:

```
split(delimiter: ",", str:"foo,bar")
```

as corresponding to https://github.com/dmn-tck/tck/blob/f212e3ade5aeeb252386cc83ac1473313503a2cc/TestCases/compliance-level-3/0067-feel-split-function/0067-feel-split-function.dmn#L75

that is a named parameter style invocation; hence, in my understanding of **10.3.2.13.5 Positional and named parameters**, applies again the principle that _unsupplied parameters are bound to null_, my understanding:

```
split(delimiter: ",", str:"foo,bar") // original
split(delimiter: ",", string: null, str:"foo,bar") // applies 10.3.2.13.5 
null // result, cannot split a null.
```

and then because trying to invoke the built-in FEEL `split()` function for a null string, you cannot split a null over `,` hence result is null.
The test is showing the non-automated, helper flag for an error is expected to be raised, which is fine [link](https://github.com/dmn-tck/tck/blob/f212e3ade5aeeb252386cc83ac1473313503a2cc/TestCases/compliance-level-3/0067-feel-split-function/0067-feel-split-function-test-01.xml#L97).

### Conclusions over the 2 linked examples beyond decision services.

Same logic applies to me, as detailed in this answer.

> trying to understand why we're treating this case differently

I don't concur they are managed differently, the same logic of 10.3.2.13.5 applies as detailed in the above.

**Comment by StrayAlien** [comment]
Hi @tarilabs  - thanks again.  

"will error when wrongly named param".  That is the _intention_ - it says it in the descriptions.  

Thanks for pointing out those tests are actually getting a false positives (ouch!!), and, according to their intention, I think they should be amended.  Apols I didn't catch that, and unfortunately nobody else did at submission time - such is life.  Those test are intended to assert that badly named params results in an error/null. There are specific tests for what happens when the param values are null (and they are named as such) - eg, in one of the example suites like here: https://github.com/dmn-tck/tck/blob/master/TestCases/compliance-level-3/0067-feel-split-function/0067-feel-split-function-test-01.xml#L104

But, I think you are saying that you believe that wrongly named params are just simply to be ignored.  Is that the case?  

If so, then how we arrived with 10 or 20 or so tests named like the above is a different matter, but when submitting those tests, that was what they were asserting on.  Most (if not all) function suites I submitted had those assertions in them.  Hence doing the same for decision services - they share the same semantics, hence, get the same assertions - they are just a function after all.

I'll ask here of the vendors: "do you ignore incorrectly named function arguments?"

**Comment by StrayAlien** [comment]
Closing this off to open a more succinct version.
