### ISSUE TITLE
Wrongly named parameters are an error - or ignore them? 

### ISSUE THREAD

**Issue by StrayAlien** [dmn-tck/tck#352]
Hi all,

We have a number of tests asserting that passing a named parameter to a function that has no matching formal parameter is an error.  I'm not meaning that missing named parameters get a null value, I mean like a typo in a param name - like `sqrt(number: 123)` (correct) vs `sqrt(numbr: 123)` (incorrect) - such that when the function/invocable formal params are scanned for the given param name none is found.

It's kind of the same as for the tests where we assert an error when we pass too many (positional) params.

The trouble is, our 'assert badly named params' tests all are giving false positives at the moment - so they are not actually asserting what they intend on asserting (apologies for that - mea culpa).  The one exception was a test I submitted in suite 0085 (discussed here: https://github.com/dmn-tck/tck/issues/349) which was not a false positive.  That was changed such that the result means badly named params are ignored and do not result in a null function result.

SIDEBAR: the reason for the false positives is that, as @tarilabs kindly pointed out, `sqrt(numbr: 123)` will result in null anyways as a _missing_ `number` param will default to a null value .. and thus the function result will be null.   

IMO wrongly named params should be treated like too many positional params, but it seems maybe other impls do not do same. I'm not religious about it, but think that erring on the side of correctness benefits all.

What do others think?

Greg.

**Comment by tarilabs** [comment]
Hi Greg,
as we discussed at length here #349 the DMN spec is clear on the execution semantic when invoking a function with named parameters, and when named parameters are missing, and as proved here: https://github.com/dmn-tck/tck/issues/349#issuecomment-565977874 and here: https://github.com/dmn-tck/tck/issues/349#issuecomment-566063458 with hand-written execution steps I did targeting your specific reference.

Now you opened a new GitHub issue and I'm happy to help further if you feel it has any value, but rather than a generic textual description, would you be kind to provide a specific, bounded example of what you mean?

I'm just trying to be helpful and to avoid going in circles (https://github.com/dmn-tck/tck/blame/master/README.md#L44), if that helps.

I'll try to give an example first.
You have hinted at calling:
`sqrt(numbr: 123)`
as explained here: https://github.com/dmn-tck/tck/issues/349#issuecomment-566063458
```
sqrt(numbr: 123) // original
sqrt(number: null, numbr: 123) // applies DMN spec 10.3.2.13.5 
null // result, cannot square root a null.
```
so would result in a `null` value (and an error message as you cannot square root the null).

What are you expecting instead?

**Comment by StrayAlien** [comment]
Hi @tarilabs - thanks.  Must be late there.  

I wasn't meaning to go around in circles.  I closed that issued off to open this one to be specific about extra/unknown named params _not_ missing ones - things got clouded there.  I really _do_ get that missing params are null-coerced and thanks for your comments.  But that is not what I am referring to.  I guess I could also refer to 'wrongly named' params as ''additional or unknown named params'.

We kind of went in circle on that other issue about missing vs extra/unknown.   Trying not to here.  So, let's focus on extra/unknown params, not missing ones.

The test I referred to 0082 was a specific example of what one might expect.  In the initial PR was asserting a null result due to an extra/unknown param on DS invocation.  Hopefully it was not also a false positive! That was changed in such a way as extra/unknown named params were ignored.  No sweat.

Perhaps a better example here might have been invoking a BKM or decision service and not a built-in func.   Hopefully this helps illustrate missing vs extra/unknown.

Let's say I have a BKM `myBkm` with two formal params `a` and `b`.

If I invoke it as `myBkm(a:1, b:2, c:3)` - what should I expect?  I would assert null and an error as `c` is an extra/unknown param.  Similar to calling it as `myBkm(1,2,3)` - which we currently assert would give an error/null - no a false positive there.

What about `myBkm(a:1, c:2)` .. etc?.  In this case `b` would be coerced to null - no probs, but we've provided an unknown param - so I would assert null and an error - which is what I did in the initial 0082 PR.

Is that any clearer? Does that illustrate what I mean between missing vs extra/unknown?

If you're in disagreement that is okay - like I said, I am not religious about it - I am not defending it. This issues was raised to ask others what they felt about extra/unknown named params.

If extra/unknown named params are to be ignored them we need to remove some tests.  If they are not to be ignored, we need to amend/remove the existing tests and likely add some more.

Greg.

**Comment by StrayAlien** [comment]
This is what led me here:

![image](https://user-images.githubusercontent.com/12524254/71753395-9ec7e180-2ed6-11ea-927c-fc195dc54769.png)

**Comment by tarilabs** [comment]
I find it a bit difficult to be clearer as the implementation of "myBkm" is not there, so we cannot do the execution by hand...

However I believe I might be getting closer to what you are trying to say, so I will give an attempt below to a working example.

Premised that despite this is referenced in:

![image](https://user-images.githubusercontent.com/1699252/71755706-3eac4d80-2e8c-11ea-9e17-e77cc4430923.png)


and

![image](https://user-images.githubusercontent.com/1699252/71755292-3521e600-2e8a-11ea-8ff7-3575fb957c67.png)

so I believe the context `s'` would behave in the way I described,

What you are actually saying is that:
```
sqrt(number: 4, extra: 123) // new example
null // result according to this thread, a null value, not 2.
```

Because accordingly to your arguments I have yes supplied the correct **_named_** parameter `number` and the square root of 4 would be 2, but because I have supplied an extra **_named_** parameter `extra` then you are argumenting this does not becomes part of the lexical clousure, but would fail the type check at the function invocation stage.

Am I understanding now your argument correctly and with a well defined working example?

I believe even in DMNv1.3 the revision of paragraph of "10.3.2.13.2 User-defined functions" does not take fully into account the passage of "10.3.2.13.5 Positional and named parameters" where it say "_If named, unsupplied parameters are bound to null._" so I believe this could be worthy a clarification in the spec.

To be clear, I am fine as long as there is a reached consensus on the definition, and I hope I given enough elements in this and the previous thread https://github.com/dmn-tck/tck/issues/349 to show why that is not (yet?) fully clear by the spec IMHO

Let me know if this new working example is more aligned with your perspective, please.

**Comment by StrayAlien** [comment]
Hi @tarilabs - many thanks for the reply.  Apols for delayed reply.

Yes - we're getting there.  The example `sqrt(number: 4, extra: 123)` returning `null` due to the extra unspecified param is what I mean.  To me that is similar to calling `sqrt(4, 123)`.  In which case the TCK would currently assert a null/error result.  

In essence, your `sqrt` example is the same the `myBkm()` given example above.  That is, a named parameter is provided that is not one of the specified formal params.  So we're good.  My thinking extends this to treating any unknown named param the same as the extra named param in your example.  

I agree the spec is not clear here and it does need clarification. Also agree that as long as we all do the same thing we're good - hence this thread.  It seems vendors are ignoring them at the moment which is okay - as long as we all do the same.

Though, my feeling is it is better to err on the side of correctness.  We're doing that with positional params at the moment so this feels the same. 

Thanks again, I do appreciate your insights.  Most welcome.

Greg.

**Comment by StrayAlien** [comment]
closing
