### ISSUE TITLE
Missing typeRefs for InputData

### ISSUE THREAD

**Issue by opatrascoiu** [dmn-tck/tck#430]
There are several places where InputData does not have a typeRef.

This  makes type inference  and validation of semantics at compile time impossible.

Our users are not allowed to execute above DMs.

I am inclining towards making InputData.variable.typeRef mandatory.

Lets discuss.

**Comment by StrayAlien** [comment]
Hi @opatrascoiu - as much as I sure like the ideas of locking things down for better typing, I think the idea of a 'compiler' and what it can or cannot do is an implementors choice / concern.  The spec does not mention 'compile' so I'm inclined to think that making mods to the spec to cater for compilation is perhaps maybe not in line with the intention there?  Happy for thoughts, but I'd be keeping it 'dynamic' and assume that an implementation may have no 'compiler' at all.

As an aside, we cater for it by having an internal 'unknown' type that everything confirms to, and it conforms to everything.  And thus, runtime checks are required for when the compiler cannot determine typing.  Some limitations apply to its usage and the compiler will complain/err in some situations.  But, in practice it seems to work and some effort / checking is deferred until runtime.

As a suggestion, rather than mandating it in the spec, I'd be voting for a) a suite of tests where the inputData have no typeRefs ... or b) alternatively (and this would be my preference), removing all typeRefs from inputData in the entire TCK _except_ for only those places where it is being tested for specifically.  Like there are some of those in this suite: https://github.com/dmn-tck/tck/pull/422 to catch input data not conforming to 'constrained types' with allowed-values somewhere in them.

Happy for thoughts.

**Comment by opatrascoiu** [comment]
@StrayAlien I think we all agree that DMN / FEEL is a typed language:
- each value belongs to a semantic domain / type
- each DRG element has a variable
- there are conformance rules & implicit conversions

Based on the above type checking is a must. It can be static checking / compile time or dynamic checking / runtime. 

For some DRGElements (e.g. Decisions) the type can be inferred at compile time or runtime. How would you perform type checking for InputData is there is no typeRef ?

**Comment by StrayAlien** [comment]
Hi @opatrascoiu / @tarilabs - my sincere apologies for missing the meeting.  I really really thought it was tonight, not last night.  I was looking forward to it actually.  Some great things to discuss.  Apologies to you and the crew - I'm feeling a little stupid about that one.  Mi culpa.

I saw the minutes and I have to say, I do disagree with the idea that we should typeRef inputs everywhere.    I think it is a slippery slope to start to think about mandating some typing to make some stuff easier.

My preference would actually be the exact opposite - that is, to _remove_ typeRefs everywhere unless they are _specifically_ part of the test - and that includes inputData elements.

I do agree that DMN / FEEL has a typed nature to it .. but it is a runtime nature, not a pre-compiled nature.  The spec caters for this by all the 'nulls' all over place - annoying as they are.  But, they are there to catch runtime type mismatches and so on. 
But, in no way does it mandate describing types in advance to make the life of a compiler or any particular implementation easy.   That is an implementor's problem / choice / challenge / opportunity.  And, it is not necessary nor required.

The conformance rules, semantic domain checking and implicit conversions can all be handed at runtime, and I believe this is the intention of the spec - hence the nulls.  If an implementor chooses to make a fantastic compiler to catch as many things as possible then great - and I think we're all doing that.  But, IMO it should not creep in to tests or the spec. 

Re "How would you perform type checking for InputData if there is no typeRef ?" 

The answer is the same way as everything else is checked at runtime, by looking at the data you have and making a type from it at runtime to check against a concrete type.  If the data is a string, then the type is a string, if the data is a number, then a number.  If the data is a context, then, at runtime, create a context type based on the data and use that for conformance / conversion.  If it is a list, and all elements are strings then it is a list<string>.  Like that, and so on, for lists of contexts containing lists etc.  It can be done fairly accurately, but some stuff will just go in the bin and end up as a null as things like `[]` operations need to know if things are a list or a context.  It gets hard then.

So, I'd vote to remove typeRefs everywhere except when they are part of the test, rather than the opposite as the spec provides for resolving these things at runtime.

**Comment by opatrascoiu** [comment]
@StrayAlien Re "How would you perform type checking for InputData if there is no typeRef ?"

Type checking (static / dynamic) means checking the actual type (type of value provide by user / data source) with the expected type. If the InputData.variable.typeRef is missing where can you get the expected type from ? It can not be inferred.

**Comment by StrayAlien** [comment]
Hi @opatrascoiu  - it does not need to be inferred.  Whether it is an inputData or not does not matter, perhaps, it is better to think of _assignments_ rather than the types of data sources.  An inputData is an 'assignment source' like any 'variable' can be.  It does not matter what type it is, it only matters what you try to assign it to.  So, if an untyped inputData has (say) a string for actual data, that is okay, but to assign it to a number argument (like as input to say the sqrt() func) then the runtime result is null.  The type does not matter, only the _assignment compatibility_ matters.  

The exact same principle applies, for example, to the assignment of expression results (like decision) to variables.  Some runtime value is being _assigned_ to something else.  So, create a runtime-type for the data that is being assigned, check if it is compatible with the type for the assignment (if known), be it a variable or a formal parameter value or whatever.  Whether the assignment source is an inputData going into a decision, or the result of a decision to variable, it does not matter.  It is essentially about runtime assignment compatibility -  the type of the source only matters when assigning it to something - and that can be checked at runtime.

I guess it is important to consider that a DMN model is perfectly valid without _any_ typeRefs in it at all - none whatsoever.  A complete and complex model may have _no_ typeRefs at all and be totally perfect.  If everything is valid and all types align then the model will execute successfully.  However, if types do not align then there will be a null assigned somewhere and that will influence the result.  But, in no way does it have to be caught at 'compile time' because, as far as the spec is concerned, there is no such thing as a compiler ...

**Comment by opatrascoiu** [comment]
Hi @tarilabs,

As discussed in our previous meeting I checked the existing tests for missing `InputData.variable.typeRef`. I found only one file 0092-feel-lambda with following InputDatas with missing typeRef:

```
input_007_1
input_011_1
input_017_1
```

**Comment by StrayAlien** [comment]
Hi @opatrascoiu / @tarilabs - I am guessing that means disagreement with my comment above?  If I may reiterate (and paraphrase) - really, I mean no offence, but I really do not believe the TCK should be imposing constraints on DMN models that are non-existent in the spec - it goes against the very idea of the TCK.  The spec does not impose that inputData elements _require_ a typeRef so therefore the TCK must not also.  TBH, I not actually sure why this idea is being entertained.  In all cases I can recall where the spec does not makes something explicit the TCK has chosen to seek clarification regarding it.

Again, I am not against the idea of making those typeRefs mandatory - as long as the spec supports it - which it does not at the moment. If it is something that needs to be clarified, then let's raise an issue and get it resolved. After RTF agreement then we can get it into the TCK, but before then, please lets not.  

No offence meant, but I feel it is the wrong thing to do.

Greg.

**Comment by tarilabs** [comment]
> I am guessing that means disagreement with my comment above? 

you are guessing wrong :) that is at least as you tagged me explicitly and I haven't had a chance to reply.

My goal is to find a _workable_ compromise that is compatible with the DMN specification and a sensible common ground for defining the tests; but sorry I didn't have a chance yet to reiterate and what was discussed in the MoM.

**Comment by opatrascoiu** [comment]
Hi  @StrayAlien @tarilabs

In the past when there were disagreements about the test cases, the compromise that @tarilabs mentioned above was reached like this:
- discuss issues in TCK
- commit only test cases we `all` agree on
- raise an RTF ticket for clarification
- once RTF ticket is resolved, add new test cases

**Comment by StrayAlien** [comment]
Thanks @opatrascoiu / @tarilabs.  I appreciate the responses.

I've been thinking about this.  I did say above "I am not against the idea of making those typeRefs mandatory", but, after considering it, I'm feeling it is not the right thing to do.

I'm not part of the RTF or DMN crew so can't offer an opinion in those forums, but here is my $0.02 (AUD) worth.  That ain't much at the moment!  (but sure is getting better) :-)

I don't feel typeRefs should be mandatory anywhere - and not on inputData.  It's a little like the typescript compiler requiring types in just specific places to make its type inference easier.  It is not necessary and doesn't make sense IMO.

Also, if a typeRef is mandatory, then it can also be the 'Any' type, which means a compiler just has to do the same thing as it does without a type.  So any effect of making the type mandatory is nullified. 

Additionally, this specification (IMO) is more to provide an outcome for business people, not developers.  Think "spaces in identifiers".  At the moment, with some design tool, a user could create a model with inputData, and execute it without thinking at all about creating types.  That input data could be complex standardised data - like, think OASIS XML, or ebXML or HL7 or somesuch - not just a string or a date.  If we make typeRefs on input mandatory then we are now adding an imposition on business users to do this extra work to define complex typeRefs as well. So, we're creating new work to do the same thing as was done previously for no real extra user benefit.  

Imagine if (say) the latest excel mandated you had to create a 'type' on some data before you could graph it.  I doubt that imposition would be welcome.

Of course, in the DMN model, the user could then just type stuff as 'Any' and get on with it.  But, again, that reduces the worth of a mandatory type.

Hopefully that makes sense. As always, happy for thoughts and comments.  And again, jus' discussing stuff.  No offence meant.

**Comment by tarilabs** [comment]
Thank you for your patience as I needed to find the time to address https://github.com/dmn-tck/tck/issues/430#issuecomment-823660531 in which I've tagged and above.

I am not sure we're speaking of the same thing, it seems to me in the last https://github.com/dmn-tck/tck/issues/430#issuecomment-823660531 we're on a tangent, the discussion originated about specifying `typeRef` for InputData nodes of DMN models under test.

Just to be clear, in the TCK we are striving for "_demonstrate compliance to the spec when evaluating a DMN model_" and focusing on concrete input and output examples.
Just to be clear, so far we are _not_ testing:
- exchange of incomplete models, even if this is described in the spec
- other expression language, even if this is (partly?) described in the spec
- Diagram Interchange layouts, even if this is described in the spec (and maybe we could, like `bpmn-miwg`)
- external Java call invocations
- external PMML call invocations
- (and possibly other areas...)

Coming back to the original topic as in https://github.com/dmn-tck/tck/issues/430#issue-857644439 : 
> There are several places where **_InputData_** does not have a typeRef.
> I am inclining towards making InputData.variable.typeRef mandatory.

(emphasis mine)

# Example1

Here is one example where I can see no problem whatsoever to specify the `InputData.variable.typeRef` for the DMN model under test:
![image](https://user-images.githubusercontent.com/1699252/116668029-30e1dc00-a99d-11eb-9c54-70a39281ac63.png)
with `can drive?` being:
```
if a person.age > 18 then true else false 
```
This example tests the FEEL evaluation including special "quirks" of the language such as non-context-free because of the space or `?` in the variable names.
The set of values you would use this test for, are always for `a person.age` being a number in the respective TCK test XML, as the designer of the DMN Model under test I can clearly specify my intent of what this test is for, and I will specify the InputData `typeRef` being a context which `age` entry is a `FEEL:number`.

# Example2

Here is a more general DMN model:
![image](https://user-images.githubusercontent.com/1699252/116669015-59b6a100-a99e-11eb-9daa-fbd70a806ffa.png)
with `sum` being:
```
a+b
```
This example tests the FEEL operator `+` which can work for all possible input types, like both `a` and `b` InputData nodes valorized as `number`, both valorized as `string`, and all combos from Table 57 currently in DMNv1.3
The set of values you would use this test for, can _be of many types_ the respective TCK test XML, as the designer of the DMN Model under test I can clearly specify my intent of what this test is for, and I will specify the InputData `typeRef="Any"`.

As both these examples shows, I think it's a fair point and meaningful to specify the `typeRef` for `InputData` nodes of the DMN model under tests

# Conclusion

I believe the compromise we discussed in https://github.com/dmn-tck/tck/discussions/431#discussion-3322550 is a fair compromise, and a good guideline:

> For DMN model under test the InputData nodes in the model SHALL specify `typeRef`
>
> The InputData `typeRef` SHOULD be as precise as possible (if the test is supplying a `number` as an input, the InputData should be `typeRef="number"`)
>
> There might be cases where:
> - the test should work _generically_ on the supplied inputs (the specific input maybe a number or maybe a string)
> - and there might be other cases where the intention of the test is to leverage the typecheck/conversion/coercion.
>
> In this and similar cases, it would be better for the DMN models under test to specify the InputData nodes `typeRef="Any"`.

as demonstrated in the above examples.

To be clear, I believe the above is a reasonable compromise between @opatrascoiu original's proposal and @StrayAlien arguments, I can see the reasons of each but we will need to find a sensible balance to move forward, and I believe the above is a **_fair and valid common ground_** in between.

**Comment by tarilabs** [comment]
> https://github.com/dmn-tck/tck/issues/430#issuecomment-822363590

concur, the only other inputData in that DMN model under test was defining the `typeRef` already:

https://github.com/dmn-tck/tck/blob/6639e37691bc1bfcc6c254d111689c2956514004/TestCases/compliance-level-3/0092-feel-lambda/0092-feel-lambda.dmn#L392

**Comment by StrayAlien** [comment]
Hi @tarilabs / @opatrascoiu - thanks.  I hope you are both well.

The summary above seems to support that where it is meaningful to the test or to signal the intent of the test then give an input a typeRef.  Sure thing.  But, I would say, in all other cases leave it empty if it has no specific bearing on the test.  I have to admit I'm still not sure why we're actually considering making it mandatory - if it enhances the meaning of the test, or is related specifically to what is being tested then sure, otherwise, why even make it 'Any'? - to my mind it does not make any sense.  Maybe I am missing something but I'm not clear on why stuff must be made mandatory. 

Though, I feel like I'm just repeating myself and I have a feeling it is maybe something you guys want to do - I see there are already mods to PRs being done so it seems to be important.  I'm kind of a believer that software "design-by-compromise" very rarely leads somewhere good, so, I'll just say do what you feel is right. No religion here.

One other thing though, in the above you mention external Java calls.  We are actually testing those in the TCK, but, I would support removing them if you guys all agree.  I don't really think Java callouts help make it a 'tech agnostic' spec.

**Comment by tarilabs** [comment]
@opatrascoiu I will close this JIRA as I believe we resolved all outstanding points on the TCK meeting 2021-05-13 and by merging the related PRs.

Feel free to reopen if something is still out of place.

The validator extension will be dealt with separately.
